language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  
before_deploy:
  - npm install
  - npm run deploy
  - rm -rf node_modules/

jobs:
  include:
    - stage: deploy
      if: branch = master
      name: "Deploy to gh-pages"
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        local_dir: dist
        on:
           branch: master