version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - deploy:
          name: Deploy on gh-pages
          command: npm run deploy    
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy